### ISSUE TITLE
Re: Collaborate?

### ISSUE THREAD

**Issue by Xanaxiel** [Toukibi/ToSAddon#15]
Hey man! I've added you as a collaborator along with @acc97862 for Tooltip Helper, feel free to collaborate!

**Comment by Xanaxiel** [comment]
Hey @Toukibi haven't heard from you, I'd like to discuss something with you (since I'm not very artistic lol), you can PM me on Discord if ever, Xanaxiel#2290

**Comment by Toukibi** [comment]
Hello. I am sorry I did not reply at all.  
  
I could not take anything action because I was totally unaware of what to do even if I said "Collaborate" and I felt that the language barrier was thick. When entering this sentence now, although checking it lightly once, it is in a state where Google translation and dictionary can not be released.  
  
I think that I do not mind depending on the discussion, even if I am in such a state. However, the reply speed etc will be slow and it may be disappointing.  
If you still do not mind, would you please contact me again?

**Comment by Xanaxiel** [comment]
Oh haha sure, I know a little bit of Japanese, but would need Google translate to assist as well, I was wondering if you have tried to use the new skins/patch for the tooltips? As we don't know when they would patch it, maybe we can use the new tooltips, I can give you access to it

**Comment by Xanaxiel** [comment]
You can check here for reference https://forum.treeofsavior.com/t/tooltip-suggestions/379529
